name: Test Coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy==1.26.0 PyYAML imblearn mne tensorflow==2.14 coverage pandas seaborn matplotlib keras-tuner

    - name: Run tests with coverage
      run: |
        python -m coverage run --source=. --omit=./tests/* -m unittest discover -s tests -p '*_test.py' -v
        python -m coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
